server:
  port: 8080

spring:
  application:
    name: cloud-gateway-mvc
  cloud:
    gateway:
      mvc:
        routes:
          - id: service-a
            uri: http://localhost:8081
            predicates:
              - Path=/service-a/**
            filters:
              - StripPrefix=1

# Custom property to hold timeout values mapped to route IDs
custom:
  gateways:
    timeouts:
      default:
        read-timeout: 33000
        connect-timeout: 33000
      service-a:
        read-timeout: 2000
        connect-timeout: 2000
