server:
  port: 8080

spring:
  application:
    name: cloud-gateway-mvc
  cloud:
    gateway:
      mvc:
        http-client:
          read-timeout: 33000
          connect-timeout: 33000
        routes:
          - id: service-a
            uri: http://localhost:8081
            predicates:
              - Path=/service-a/**
            filters:
              - StripPrefix=1
              - name: Timeout
                args:
                  responseTimeout: 2000
                  connectTimeout: 2000
          - id: service-b
            uri: http://localhost:8081
            predicates:
              - Path=/service-b/**
            filters:
              - StripPrefix=1
              - name: Timeout
                args:
                  responseTimeout: 3000
                  connectTimeout: 3000
          - id: service-c
            uri: http://localhost:8081
            predicates:
              - Path=/service-c/**
            filters:
              - StripPrefix=1
              - name: Timeout
                args:
                  responseTimeout: 4000
                  connectTimeout: 4000
